name: fnet
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - cython
  - matplotlib
  - numpy
  - pandas
  - pip
  - pytest
  - python=3.6
  - pytorch
  - scipy
  - tifffile
  - torchvision
  - tqdm
  - pip:
    - czifile==0.1.5
