name: fnet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pytorch=0.4.0
  - torchvision=0.1.8
  - cuda91=1.0
  - jupyter=1.0.0
  - matplotlib=2.1.1
  - pandas>=0.21.1
  - tqdm=4.19.5
  - scikit-learn=0.19.1
  - tifffile=0.15
  - pip:
    - argschema
