name: fnet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cuda91=1.0
  - matplotlib=2.1.1
  - pandas=0.23.4
  - pytorch=0.4.0
  - tifffile=0.15
  - torchvision=0.1.8
  - tqdm=4.19.5
