name: fnet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - matplotlib=2.1.1
  - pandas=0.23.4
  - pip=10.0.1
  - python=3.6
  - pytorch=0.4.0
  - scipy=1.1.0
  - tifffile=0.15
  - torchvision=0.1.8
  - tqdm=4.19.5
  - pip:
    - czifile==0.1.5
